"""Add video detection tables

Revision ID: 942effc5d261
Revises: 08a7fdb06b59
Create Date: 2025-12-24 19:06:13.427537

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '942effc5d261'
down_revision = '08a7fdb06b59'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_filename', sa.String(length=255), nullable=False),
    sa.Column('video_path', sa.String(length=500), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('fps', sa.Float(), nullable=True),
    sa.Column('total_frames', sa.Integer(), nullable=True),
    sa.Column('resolution_width', sa.Integer(), nullable=True),
    sa.Column('resolution_height', sa.Integer(), nullable=True),
    sa.Column('file_size_mb', sa.Float(), nullable=True),
    sa.Column('processing_status', sa.String(length=20), nullable=False),
    sa.Column('frames_processed', sa.Integer(), nullable=True),
    sa.Column('total_faces_detected', sa.Integer(), nullable=True),
    sa.Column('unique_criminals_matched', sa.Integer(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('processing_completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('camera_id', sa.String(length=50), nullable=True),
    sa.Column('annotated_video_path', sa.String(length=500), nullable=True),
    sa.Column('summary_report', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('video_detections', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_video_detections_upload_date'), ['upload_date'], unique=False)

    op.create_table('video_frame_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_detection_id', sa.Integer(), nullable=False),
    sa.Column('frame_number', sa.Integer(), nullable=False),
    sa.Column('timestamp_seconds', sa.Float(), nullable=False),
    sa.Column('faces_detected', sa.Integer(), nullable=True),
    sa.Column('criminal_id', sa.Integer(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('face_coordinates', sa.String(length=100), nullable=True),
    sa.Column('frame_image_path', sa.String(length=500), nullable=True),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['criminal_id'], ['criminals.id'], ),
    sa.ForeignKeyConstraint(['video_detection_id'], ['video_detections.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('face_encodings', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('face_encodings', schema=None) as batch_op:
        batch_op.alter_column('is_primary',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    op.drop_table('video_frame_detections')
    with op.batch_alter_table('video_detections', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_video_detections_upload_date'))

    op.drop_table('video_detections')
    # ### end Alembic commands ###
